name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-container:
    name: Build and Push r3voc-tallylight-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Main Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./tallylight-backend
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./tallylight-backend/Dockerfile
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            CI_RUN_ID=${{ github.run_id }}
